config/routes.rb
Rails.application.routes.draw do
  root to: 'engines#index'
  resources :engines

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :engine, optional: true
end

app/models/engine.rb
class Engine < ApplicationRecord
    has_one :car, dependent: :destroy
    accepts_nested_attributes_for :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: [:show, :edit, :update, :destroy]
  def index
    @engines = Engine.all
  end

  def new
    @engine = Engine.new
    @engine.build_car
  end

  def create
    @engine = Engine.new(params_engine)
    if @engine.save
      redirect_to engines_path, notice: "Carro e motor salvos com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @engine.update(params_engine)
      redirect_to engines_path, notice: "O carro #{@engine.car.model.capitalize} atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @engine.destroy
      redirect_to engines_path, notice: "O carro #{@engine.car.model} foi excluído com sucesso!"
    else
      render :index
    end
  end

  private
    def params_engine
      params.require(:engine).permit(:cylinders, :cylinder_positioning, :liters, :notes,
        car_attributes: [
          :brand,
          :model,
          :color,
          :engine_id
        ]
      )
    end
    
    def set_engine 
      @engine = Engine.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
    
end

app/helpers/engines_helper.rb
module EnginesHelper
    def brand(car)
        car.brand.nil? ? '' : (link_to "#{car.brand.capitalize}", engine_path(car.id))
    end

    def model(car)
        car.model.nil? ? '' : car.model.capitalize
    end

    def color(car)
        car.color.nil? ? '' : car.color.capitalize
    end

    def cylinder_positioning(engine)
        engine.cylinder_positioning.nil? ? '' : engine.cylinder_positioning.capitalize
    end

    def notes(engine)
        engine.notes.nil? ? '' : engine.notes.capitalize
    end
end

app/views/engines/_car_fields.html.erb
<div class="col-md-12">
    <%= f.label :brand, "Marca", class: "form-label" %>
    <%= f.text_field :brand, class: "form-control" %>
</div>
<div class="col-md-12">
    <%= f.label :model, "Modelo", class: "form-label" %>
    <%= f.text_field :model, class: "form-control" %>
</div>
<div class="col-md-12">
    <%= f.label :color, "Cor", class: "form-label" %>
    <%= f.text_field :color, class: "form-control" %>
</div>

app/views/engines/_form.html.erb
<%= render partial: 'engines/form_steps_js' %>
<%= form_with model: @engine do |f| %>
    <div style="margin:auto" class="col-md-6">
        <div id="car_step" class="card shadow md-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Carro</h6>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <%= f.fields_for :car do |car_form| %>    
                        <%= render "engines/car_fields", f: car_form %>                            
                    <% end %>
                    <div class="clearfix">&nbsp;</div>
                    <div class="col-md-12" align="right">
                        <%= link_to "Voltar", engines_path, class: 'btn btn-secondary' %>
                        <button onclick="engine_step();" type="button" class="btn btn-primary">Próximo</button>
                    </div>
                </div>
            </div>
        </div>

        <div id="engine_step" class="card shadow md-4" style="display:none;">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Motor</h6>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <div class="col-md-12">
                        <%= f.label :cylinders, "Cilindros", class: "form-label" %>
                        <%= f.number_field :cylinders, class: "form-control", min: 0 %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :cylinder_positioning, "Posicionamento dos Cilindros", class: "form-label" %>
                        <%= f.text_field :cylinder_positioning, class: "form-control" %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :liters, "Litragem", class: "form-label" %>
                        <%= f.number_field :liters, class: "form-control", min: 0 %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :notes, "Observação", class: "form-label" %>
                        <%= f.text_area :notes, class: "form-control" %>
                    </div>
                    <div class="clearfix">&nbsp;</div>
                </div>
                <div class="col-md-12" align="right">
                    <button onclick="car_step();" type="button" class="btn btn-primary">Anterior</button>
                    <%= f.submit "Salvar", class: 'btn btn-success' %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/engines/_form_steps_js.html.erb
<script type="text/javascript">
    function car_step() {
        $('#car_step').show();
        $('#engine_step').hide();
    }

    function engine_step() {
        $('#car_step').hide();
        $('#engine_step').show();
    }
</script>

app/views/engines/edit.html.erb
<h1 class="text-center">Editar carro e motor</h1>
<%= render partial: 'engines/form' %>

app/views/engines/index.html.erb
<div class="text-center">
    <h1>Tipos de carros e seus motores</h1>
    <p><%= link_to "Novo carro/motor", new_engine_path, class: 'btn btn-success' %><p>
</div>
<div style="margin:auto" class="col-md-12">
    <div class="card shadow md-12">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Carro</h6>
        </div>
        <table class="table table-striped">
            <thead>
                <td>Marca</td>
                <td>Modelo</td>
                <td>Cor</td>
                <td>Cilindros</td>
                <td>Posicionamento dos Cilindros</td>
                <td>Litragem</td>
                <td>Observação</td>
                <td>Opções</td>
            </thead>
            <tbody>
                <% @engines.each do |engine| %>
                    <tr>
                        <td><%= brand(engine.car) %></p></td>
                        <td><%= model(engine.car) %></p></td>
                        <td><%= color(engine.car) %></p></td>
                        <td><%= engine.cylinders %></td>
                        <td><%= cylinder_positioning(engine) %></td>
                        <td><%= engine.liters %></td>
                        <td><%= notes(engine) %></td>
                        <td>
                            <%= link_to "Editar", edit_engine_path(engine.id) %>
                            <%= link_to "Excluir", engine_path(engine.id), method: :delete, 
                                data: {confirm: "Deseja excluir o carro #{engine.car.model}?"} %>     
                        </td>                    
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/engines/new.html.erb
<h1 class="text-center">Criar novo carro e motor</h1>
<%= render partial: 'engines/form' %>

app/views/engines/show.html.erb
<div class="text-center">
    <h1>Tipo de carro e motor</h1>
    <p><%= link_to "Novo carro/motor", new_engine_path, class: 'btn btn-success' %><p>
</div>
<div style="margin:auto" class="col-md-12">
    <div class="card shadow md-12">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">&nbsp</h6>
        </div>
        <table class="table table-striped">
            <thead>
                <td>Marca</td>
                <td>Modelo</td>
                <td>Cor</td>
                <td>Cilindros</td>
                <td>Posicionamento dos Cilindros</td>
                <td>Litragem</td>
                <td>Observação</td>
            </thead>
            <tbody>
                <tr>
                    <td><%= brand(@engine.car) %></p></td>
                    <td><%= model(@engine.car) %></p></td>
                    <td><%= color(@engine.car) %></p></td>
                    <td><%= @engine.cylinders %></td>
                    <td><%= cylinder_positioning(@engine) %></td>
                    <td><%= @engine.liters %></td>
                    <td><%= notes(@engine) %></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="text-center">
        <div class="clearfix">&nbsp;</div>
        <%= link_to "Voltar", engines_path, class: 'btn btn-secondary' %>
    <div>
</div>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeveloperTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <%= render partial: 'layouts/partials/notifications' %>
</html>

app/views/layouts/partials/_notifications.html.erb
<% if notice %>
    <script>
        $.bootstrapGrowl("<%= notice %>", {
        type: 'success', // (null, 'info', 'danger', 'success')
        align: 'right', // ('left', 'right', or 'center')
        allow_dismiss: true, // If true then will display a cross to close the popup.
        stackup_spacing: 10 // spacing between consecutively stacked growls.
        });
  </script>
<% end %>